deploy:
  provider: divshot
  environment:
    master: development
  skip_cleanup: true
  api_key:
    secure: MbdCF4H+r6H4tK3lS9OAGvZlAU9ahcMksJ5LvvFaGWadpk8LvYRD4aGqEhNqXJHpVxgwef2bKbrrHqSNNFv81iFbKkd7NHB2/nH9otxllAK3QP5emgnYQ/z7cHPox1EZz0ga5mBY3pU8CZZ4oX25R1pXYrKzQ9P8G7c/6NPDF1g=
